# Copyright 2023 Logan Magee
#
# SPDX-License-Identifier: Apache-2.0

[workspace]
members = ["cli", "ina", "sufsort"]
resolver = "3"

[profile.release]
strip = true
lto = true
codegen-units = 1

[profile.cdylib-release]
inherits = "release"
panic = "abort"
